#!/usr/bin/env bats
#
# orphan_review.bats — P0-T04: reviewed-orphan input is untrusted input.
#
# --remove-orphans-from is the one place where a user-supplied list of paths
# reaches the removal code. Every test here is an attempt to make that list say
# something the scanner would never have produced.

load 'test_helper'

source_lib() {
  load_lib
  LOG_FILE="$TEST_TMPDIR/test.log"
  : > "$LOG_FILE"
}

# See path_api.bats: `run` uses a subshell, so a global set by the command is
# invisible afterwards. ORPHAN_DENY_REASON is exactly such a global.
validate_fails() {
  if validate_orphan_target "$@"; then
    echo "expected validate_orphan_target to refuse: $1" >&2
    return 1
  fi
  return 0
}

APPSUP() { printf '%s' "$FAKE_HOME/Library/Application Support"; }

# Write a review file with the header this tool requires, then one line per
# argument, verbatim.
write_review() {
  local f="$TEST_TMPDIR/review.txt" line
  {
    printf '# mimi-orphan-review v1\n'
    printf '# generated by a test\n'
    for line in "$@"; do
      printf '%s\n' "$line"
    done
  } > "$f"
  printf '%s' "$f"
}

# A review file with no header at all.
write_review_unmarked() {
  local f="$TEST_TMPDIR/review-bad.txt" line
  : > "$f"
  for line in "$@"; do
    printf '%s\n' "$line" >> "$f"
  done
  printf '%s' "$f"
}

# ---------------------------------------------------------------------------
# The traversal hole this task exists to close
# ---------------------------------------------------------------------------

@test "traversal: '..' in a review line cannot reach outside the orphan roots" {
  # The exact shape of the original defect: the old code compared this raw
  # string against "$HOME/Library/Application Support/"* — which it matches —
  # and then handed it straight to rm.
  local victim="$FAKE_HOME/Library/Caches/victim"
  mkdir -p "$victim"
  printf 'precious\n' > "$victim/data"

  local f
  f="$(write_review "$(APPSUP)/../../Library/Caches/victim")"

  # --only orphans so that no other category can be the reason the victim
  # survives. cat_orphans itself is skipped without --include-orphans; the
  # review file is processed either way.
  run_clean --clean --yes --only orphans --remove-orphans-from "$f"
  [ -f "$victim/data" ]
  echo "$output" | grep -q 'traversal'
}

@test "traversal: '..' cannot reach outside HOME entirely" {
  local outside="${TEST_TMPDIR%/*}/outside-$$"
  mkdir -p "$outside"
  printf 'precious\n' > "$outside/data"

  local f
  f="$(write_review "$(APPSUP)/../../../../$(basename "${TEST_TMPDIR%/*}")/outside-$$")"

  run_clean --clean --yes --remove-orphans-from "$f"
  [ -f "$outside/data" ]
  verify_sentinels
  rm -rf "$outside"
}

@test "traversal: validate_orphan_target reports the traversal reason code" {
  source_lib
  mkdir -p "$FAKE_HOME/Library/Caches/victim"
  validate_fails "$(APPSUP)/../../Library/Caches/victim"
  [ "$ORPHAN_DENY_REASON" = "traversal" ]
}

# ---------------------------------------------------------------------------
# A malformed file cannot broaden scope
# ---------------------------------------------------------------------------

@test "header: a file without the format marker is refused outright" {
  local target
  target="$(APPSUP)/com.example.gone"
  mkdir -p "$target"

  local f
  f="$(write_review_unmarked "$target")"

  run_clean --clean --yes --remove-orphans-from "$f"
  [ -d "$target" ]
  echo "$output" | grep -q 'mimi-orphan-review v1'
}

@test "header: a marked file produced by a real scan is accepted end to end" {
  local target
  target="$(APPSUP)/com.example.definitelygone"
  mkdir -p "$target"
  printf 'x\n' > "$target/data"

  # Generate the review file the way a user would.
  run_clean --scan --only orphans --include-orphans --no-log
  [ "$status" -eq 0 ]

  local generated
  generated="$(grep -rl 'mimi-orphan-review v1' "$FAKE_HOME/Library/Logs/mimi" 2>/dev/null | head -1)"
  [ -n "$generated" ]
  grep -qx "$target" "$generated"

  run_clean --clean --yes --remove-orphans-from "$generated"
  [ "$status" -eq 0 ]
  [ ! -e "$target" ]
}

@test "scope: a path outside every orphan root is refused" {
  source_lib
  mkdir -p "$FAKE_HOME/Library/Caches/thing"
  validate_fails "$FAKE_HOME/Library/Caches/thing"
  [ "$ORPHAN_DENY_REASON" = "not-orphan-root" ]
}

@test "scope: a path deeper than a direct child is refused" {
  source_lib
  mkdir -p "$(APPSUP)/com.example.app/Inner"
  validate_fails "$(APPSUP)/com.example.app/Inner"
  [ "$ORPHAN_DENY_REASON" = "not-direct-child" ]
}

@test "scope: the orphan root directory itself is refused" {
  source_lib
  validate_fails "$(APPSUP)"
  [ "$ORPHAN_DENY_REASON" = "not-orphan-root" ]
}

@test "scope: HOME itself is refused" {
  source_lib
  validate_fails "$FAKE_HOME"
  [ "$ORPHAN_DENY_REASON" = "forbidden" ]
}

@test "scope: a relative path is refused" {
  source_lib
  mkdir -p "$(APPSUP)/com.example.app"
  validate_fails "Library/Application Support/com.example.app"
  [ "$ORPHAN_DENY_REASON" = "missing" ]
}

@test "scope: a direct child of a real orphan root validates" {
  source_lib
  mkdir -p "$(APPSUP)/com.example.app"
  validate_orphan_target "$(APPSUP)/com.example.app"
  [ "$ORPHAN_CANONICAL" = "$(cd "$(APPSUP)" && pwd -P)/com.example.app" ]
}

@test "scope: every ORPHAN_ROOTS location is accepted for a direct child" {
  source_lib
  local spec root
  for spec in "${ORPHAN_ROOTS[@]}"; do
    root="${spec%%::*}"
    mkdir -p "$root/com.example.child"
    validate_orphan_target "$root/com.example.child"
  done
}

@test "scope: a whitelisted path is refused with its own reason code" {
  source_lib
  mkdir -p "$(APPSUP)/com.example.app"
  WHITELIST=("$(APPSUP)/com.example.app")
  validate_fails "$(APPSUP)/com.example.app"
  [ "$ORPHAN_DENY_REASON" = "whitelisted" ]
}

@test "scope: a whitelist entry does not protect a same-prefix sibling" {
  source_lib
  mkdir -p "$(APPSUP)/com.example.app" "$(APPSUP)/com.example.app2"
  WHITELIST=("$(APPSUP)/com.example.app")
  validate_orphan_target "$(APPSUP)/com.example.app2"
}

@test "scope: a missing path is refused before anything else is checked" {
  source_lib
  validate_fails "$(APPSUP)/never-existed"
  [ "$ORPHAN_DENY_REASON" = "missing" ]
}

@test "scope: a symlink under an orphan root is unlinked, its target survives" {
  local outside="${TEST_TMPDIR%/*}/outside-$$"
  mkdir -p "$outside"
  printf 'precious\n' > "$outside/data"
  ln -s "$outside" "$(APPSUP)/com.example.link"

  local f
  f="$(write_review "$(APPSUP)/com.example.link")"

  run_clean --clean --yes --remove-orphans-from "$f"
  [ ! -L "$(APPSUP)/com.example.link" ]
  [ -f "$outside/data" ]
  verify_sentinels
  rm -rf "$outside"
}

# ---------------------------------------------------------------------------
# "#" is a comment only in the first column
# ---------------------------------------------------------------------------

@test "comments: a # inside a filename is part of the name, not a comment" {
  local target
  target="$(APPSUP)/com.example.app#1"
  mkdir -p "$target"
  printf 'x\n' > "$target/data"
  # The old code truncated this line at the "#", leaving
  # ".../com.example.app", which does not exist — so the real folder was never
  # removed and the user was told nothing.
  local decoy
  decoy="$(APPSUP)/com.example.app"
  mkdir -p "$decoy"
  printf 'keep\n' > "$decoy/data"

  local f
  f="$(write_review "$target")"

  run_clean --clean --yes --remove-orphans-from "$f"
  [ ! -e "$target" ]
  [ -f "$decoy/data" ]
}

@test "comments: a # in the first column keeps the line out of the run" {
  local target
  target="$(APPSUP)/com.example.commented"
  mkdir -p "$target"
  printf 'x\n' > "$target/data"

  local f
  f="$(write_review "#$target")"

  run_clean --clean --yes --remove-orphans-from "$f"
  [ -f "$target/data" ]
}

@test "comments: a # after leading whitespace still comments the line out" {
  local target
  target="$(APPSUP)/com.example.indented"
  mkdir -p "$target"
  printf 'x\n' > "$target/data"

  local f
  f="$(write_review "   # $target")"

  run_clean --clean --yes --remove-orphans-from "$f"
  [ -f "$target/data" ]
}

@test "comments: a blank line is ignored" {
  source_lib
  local f
  f="$(write_review "" "   ")"
  REMOVE_ORPHANS_FILE="$f"
  MODE="scan"
  run process_orphans_review_file
  [ "$status" -eq 0 ]
  echo "$output" | grep -q 'nothing to remove'
}

# ---------------------------------------------------------------------------
# Special characters survive exactly
# ---------------------------------------------------------------------------

@test "filenames: spaces, glob characters, dashes and unicode round-trip exactly" {
  local base names n
  base="$(APPSUP)"
  names=(
    "com.example.with spaces"
    "com.example.star*glob"
    "com.example.brackets[abc]"
    "-com.example.leading-dash"
    "com.example.café-ünïcode-日本語"
    "com.example.has'quote"
    'com.example.has$dollar'
    "com.example.semi;colon"
  )
  for n in "${names[@]}"; do
    mkdir -p "$base/$n"
    printf 'x\n' > "$base/$n/data"
  done

  local f
  f="$(write_review "${names[@]/#/$base/}")"

  run_clean --clean --yes --remove-orphans-from "$f"
  for n in "${names[@]}"; do
    [ ! -e "$base/$n" ]
  done
  assert_fixture_sentinel_intact
}

@test "filenames: a trailing space is preserved when that is the real name" {
  source_lib
  local name
  name="$(APPSUP)/com.example.trailing "
  mkdir -p "$name"
  validate_orphan_target "$name"
  [ "$ORPHAN_CANONICAL" = "$(cd "$(APPSUP)" && pwd -P)/com.example.trailing " ]
}

@test "filenames: trailing whitespace is stripped only when that makes the path resolve" {
  local target
  target="$(APPSUP)/com.example.notrailing"
  mkdir -p "$target"
  printf 'x\n' > "$target/data"

  # An editor added a trailing space to a name that has none.
  local f
  f="$(write_review "$target   ")"

  run_clean --clean --yes --remove-orphans-from "$f"
  [ ! -e "$target" ]
}

@test "filenames: a candidate whose name contains a newline is reported, not listed" {
  source_lib
  local nl name
  nl='
'
  name="com.example.two${nl}lines"
  mkdir -p "$(APPSUP)/$name"

  ORPHAN_CANDIDATE_PATHS=("$(APPSUP)/$name")
  ORPHAN_CANDIDATE_TOKENS=("com.example.twolines")
  ORPHAN_CANDIDATE_KINDS=("plain")
  ORPHAN_CANDIDATE_TIERS=("review")

  write_orphans_review_file "$TEST_TMPDIR/out.txt"
  [ "$ORPHAN_REVIEW_SKIPPED" -eq 1 ]
  grep -q 'NOT LISTED' "$TEST_TMPDIR/out.txt"
  # Neither half of the name may appear as a bare path line.
  ! grep -qx "$(APPSUP)/com.example.two" "$TEST_TMPDIR/out.txt"
  ! grep -qx "lines" "$TEST_TMPDIR/out.txt"
}

# ---------------------------------------------------------------------------
# Revalidation immediately before the action
# ---------------------------------------------------------------------------

@test "revalidation: a target replaced after validation is not removed" {
  source_lib
  MODE="clean"
  ASSUME_YES=1
  local target
  target="$(APPSUP)/com.example.swapped"
  mkdir -p "$target"
  printf 'old\n' > "$target/old"

  REMOVE_ORPHANS_FILE="$(write_review "$target")"

  # dir_size_kb is called once per queued item while the list is printed,
  # which is after validation and before the removal loop.
  dir_size_kb() {
    if [ ! -f "$target/planted" ]; then
      rm -rf "$target"
      mkdir -p "$target"
      printf 'planted\n' > "$target/planted"
    fi
    printf '1'
  }

  run process_orphans_review_file
  [ -f "$target/planted" ]
  echo "$output" | grep -q 'identity-changed'
}

@test "revalidation: a target whitelisted after validation is not removed" {
  source_lib
  MODE="clean"
  local target
  target="$(APPSUP)/com.example.lateWhitelist"
  mkdir -p "$target"
  printf 'x\n' > "$target/data"

  REMOVE_ORPHANS_FILE="$(write_review "$target")"

  # The whitelist changes while the confirmation prompt is on screen, which is
  # precisely the unbounded pause the revalidation exists to cover. `confirm`
  # is called directly rather than inside a command substitution, so an
  # assignment here survives into the removal loop.
  confirm() {
    WHITELIST=("$target")
    return 0
  }

  run process_orphans_review_file
  [ -f "$target/data" ]
  echo "$output" | grep -q 'whitelisted'
}

# ---------------------------------------------------------------------------
# Modes and reporting
# ---------------------------------------------------------------------------

@test "mode: scan lists queued items without deleting them" {
  local target
  target="$(APPSUP)/com.example.scanonly"
  mkdir -p "$target"
  printf 'x\n' > "$target/data"

  local f
  f="$(write_review "$target")"

  run_clean --scan --remove-orphans-from "$f"
  [ "$status" -eq 0 ]
  [ -f "$target/data" ]
  echo "$output" | grep -q 'nothing deleted'
}

@test "reporting: each refused line names a stable reason code" {
  local f
  mkdir -p "$FAKE_HOME/Library/Caches/thing" "$(APPSUP)/com.example.app/Inner"
  f="$(write_review \
    "$FAKE_HOME/Library/Caches/thing" \
    "$(APPSUP)/com.example.app/Inner" \
    "$(APPSUP)/../../Library/Caches/thing" \
    "$(APPSUP)/never-existed")"

  run_clean --scan --remove-orphans-from "$f"
  echo "$output" | grep -q 'not-orphan-root'
  echo "$output" | grep -q 'not-direct-child'
  echo "$output" | grep -q 'traversal'
  echo "$output" | grep -q 'missing'
  echo "$output" | grep -q '3 line(s) were refused'
}

@test "reporting: a nonexistent review file is an error, not a silent no-op" {
  run_clean --clean --yes --remove-orphans-from "$TEST_TMPDIR/nope.txt"
  [ "$status" -ne 0 ]
}
